version: 2.1
orbs:
  node: circleci/node@4.5.1
  aws-cli: circleci/aws-cli@2.0.3
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.0
jobs:
  build_and_deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-elastic-beanstalk/setup
      - aws-cli/setup
      - run:
          name: backend_install_node_modules
          command: npm run backend-install
      - run:
          name: backend_build
          command: npm run backend-build
      - run:
          name: frontend_install_node_modules
          command: npm run frontend-install
      - run:
          name: frontend_build
          command: npm run frontend-build
      - run:
          name: backend_deploy
          command: npm run backend-deploy
      - run:
          name: frontend_deploy
          command: npm run frontend-deploy
workflows:
  udagram-deployment:
    jobs:
      - build_and_deploy
